ALTER TABLE EQUIPE 
ADD CONSTRAINT FK_EQUIPE_IdCandidat FOREIGN KEY (IdCandidat) REFERENCES Candidat(IdCandidat);

ALTER TABLE PERSONNE 
ADD CONSTRAINT FK_PERSONNE_IdCandidat FOREIGN KEY (IdCandidat) REFERENCES Candidat(IdCandidat);

ALTER TABLE INSCRIRE 
ADD CONSTRAINT FK_INSCRIRE_IdCandidat FOREIGN KEY (IdCandidat) REFERENCES Candidat(IdCandidat),
ADD CONSTRAINT FK_INSCRIRE_IdCompetition FOREIGN KEY (IdCompetition) REFERENCES Competition(IdCompetition);

ALTER TABLE APPARTENIR 
ADD CONSTRAINT FK_APPARTENIR_IdCandidatpersonne FOREIGN KEY (IdCandidatpersonne) REFERENCES Candidat(IdCandidat),
ADD CONSTRAINT FK_APPARTENIR_IdCandidatequpe FOREIGN KEY (IdCandidatequipe) REFERENCES Candidat(IdCandidat);